// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys;

public partial class Configuracion
{
    public int Id { get; set; }

    public int? EmpresaId { get; set; }

    public string Clave { get; set; }

    public string Valor { get; set; }

    public string Descripcion { get; set; }

    public virtual Empresa Empresa { get; set; }
}