// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class ConfiguracionConfiguration : IEntityTypeConfiguration<Configuracion>
    {
        public void Configure(EntityTypeBuilder<Configuracion> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Configur__3214EC0740CCCD06");

            entity.ToTable("Configuracion");

            entity.HasIndex(e => new { e.EmpresaId, e.Clave }, "UQ_Configuracion_Empresa_Clave").IsUnique();

            entity.Property(e => e.Clave)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Descripcion).HasMaxLength(200);
            entity.Property(e => e.Valor).IsRequired();

            entity.HasOne(d => d.Empresa).WithMany(p => p.Configuracions)
                .HasForeignKey(d => d.EmpresaId)
                .HasConstraintName("FK__Configura__Empre__5224328E");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Configuracion> entity);
    }
}
