// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class EnviosDGIIConfiguration : IEntityTypeConfiguration<EnviosDGII>
    {
        public void Configure(EntityTypeBuilder<EnviosDGII> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__EnviosDG__3214EC076137A979");

            entity.ToTable("EnviosDGII");

            entity.Property(e => e.CodigoRespuesta).HasMaxLength(10);
            entity.Property(e => e.EstadoEnvio)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.FechaEnvio).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Intentos).HasDefaultValue(1);
            entity.Property(e => e.MensajeRespuesta).HasMaxLength(500);
            entity.Property(e => e.RequestXML)
                .IsRequired()
                .HasColumnType("xml");
            entity.Property(e => e.ResponseXML).HasColumnType("xml");
            entity.Property(e => e.TrackId)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Factura).WithMany(p => p.EnviosDGIIs)
                .HasForeignKey(d => d.FacturaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EnviosDGI__Factu__45BE5BA9");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EnviosDGII> entity);
    }
}
