// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class FacturaConfiguration : IEntityTypeConfiguration<Factura>
    {
        public void Configure(EntityTypeBuilder<Factura> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Facturas__3214EC0733403BBF");

            entity.HasIndex(e => e.NCF, "UQ__Facturas__C7DE1C60CC8C4655").IsUnique();

            entity.Property(e => e.Estado)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pendiente");
            entity.Property(e => e.FechaActualizacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.FechaEmision).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ItbisTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MontoTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NCF)
                .IsRequired()
                .HasMaxLength(19);
            entity.Property(e => e.OtrosImpuestos)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TrackId).HasMaxLength(50);
            entity.Property(e => e.XmlGenerado).HasColumnType("xml");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Facturas__Client__32AB8735");

            entity.HasOne(d => d.Empresa).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.EmpresaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Facturas__Empres__31B762FC");

            entity.HasOne(d => d.TipoECF).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.TipoECFId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Facturas__TipoEC__339FAB6E");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Factura> entity);
    }
}
