// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class TiposECFConfiguration : IEntityTypeConfiguration<TipoECF>
    {
        public void Configure(EntityTypeBuilder<TipoECF> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__TiposECF__3214EC07BC4E39DD");

            entity.ToTable("TiposECF");

            entity.HasIndex(e => e.Codigo, "UQ__TiposECF__06370DAC5AFBFC1B").IsUnique();

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(5);
            entity.Property(e => e.Descripcion).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TipoECF> entity);
    }
}
