// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class CertificadosDigitaleConfiguration : IEntityTypeConfiguration<CertificadosDigitale>
    {
        public void Configure(EntityTypeBuilder<CertificadosDigitale> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Certific__3214EC07D2D06BC3");

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.Archivo).IsRequired();
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Empresa).WithMany(p => p.CertificadosDigitales)
                .HasForeignKey(d => d.EmpresaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Certifica__Empre__440B1D61");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CertificadosDigitale> entity);
    }
}
