// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class ConsultasEstadoConfiguration : IEntityTypeConfiguration<ConsultasEstado>
    {
        public void Configure(EntityTypeBuilder<ConsultasEstado> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Consulta__3214EC07544EBFB2");

            entity.ToTable("ConsultasEstado");

            entity.Property(e => e.Estado).HasMaxLength(50);
            entity.Property(e => e.FechaConsulta).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.TrackId).HasMaxLength(100);

            entity.HasOne(d => d.Factura).WithMany(p => p.ConsultasEstados)
                .HasForeignKey(d => d.FacturaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Consultas__Factu__5AEE82B9");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ConsultasEstado> entity);
    }
}
