// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class EmpresaConfiguration : IEntityTypeConfiguration<Empresa>
    {
        public void Configure(EntityTypeBuilder<Empresa> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Empresas__3214EC0727F438F5");

            entity.HasIndex(e => e.RNC, "UQ__Empresas__CAFF6950716AA3CF").IsUnique();

            entity.Property(e => e.Ambiente)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Direccion).HasMaxLength(255);
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.RNC)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Telefono).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Empresa> entity);
    }
}
