// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class EnviosDGIIConfiguration : IEntityTypeConfiguration<EnviosDGII>
    {
        public void Configure(EntityTypeBuilder<EnviosDGII> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__EnviosDG__3214EC076CF83E2C");

            entity.ToTable("EnviosDGII");

            entity.Property(e => e.Estado)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.FechaEnvio).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.TrackId).HasMaxLength(100);

            entity.HasOne(d => d.Factura).WithMany(p => p.EnviosDGIIs)
                .HasForeignKey(d => d.FacturaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__EnviosDGI__Factu__571DF1D5");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EnviosDGII> entity);
    }
}
