// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class FacturaDetalleConfiguration : IEntityTypeConfiguration<FacturaDetalle>
    {
        public void Configure(EntityTypeBuilder<FacturaDetalle> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__FacturaD__3214EC072592C652");

            entity.Property(e => e.Cantidad).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ITBIS)
                .HasComputedColumnSql("(([Cantidad]*[PrecioUnitario])*([TasaITBIS]/(100)))", true)
                .HasColumnType("decimal(38, 6)");
            entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.SubTotal)
                .HasComputedColumnSql("([Cantidad]*[PrecioUnitario])", true)
                .HasColumnType("decimal(37, 4)");
            entity.Property(e => e.TasaITBIS).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.Total)
                .HasComputedColumnSql("([Cantidad]*[PrecioUnitario]+([Cantidad]*[PrecioUnitario])*([TasaITBIS]/(100)))", true)
                .HasColumnType("decimal(38, 5)");

            entity.HasOne(d => d.Factura).WithMany(p => p.FacturaDetalles)
                .HasForeignKey(d => d.FacturaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__FacturaDe__Factu__52593CB8");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FacturaDetalle> entity);
    }
}
