// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class FacturaConfiguration : IEntityTypeConfiguration<Factura>
    {
        public void Configure(EntityTypeBuilder<Factura> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Facturas__3214EC074065C690");

            entity.HasIndex(e => e.ClienteId, "IX_Facturas_ClienteId");

            entity.HasIndex(e => e.EmpresaId, "IX_Facturas_EmpresaId");

            entity.HasIndex(e => e.Estado, "IX_Facturas_Estado");

            entity.HasIndex(e => e.NumeroECF, "IX_Facturas_NumeroECF");

            entity.HasIndex(e => e.NumeroECF, "UQ__Facturas__D8598D3AA0C979AD").IsUnique();

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Estado)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.MontoGravado).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MontoImpuestos).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.MontoTotal).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.NumeroECF)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TipoECF)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.TrackId).HasMaxLength(100);
            entity.Property(e => e.XmlFirmado).HasColumnType("xml");
            entity.Property(e => e.XmlGenerado).HasColumnType("xml");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Facturas__Client__4F7CD00D");

            entity.HasOne(d => d.Empresa).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.EmpresaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Facturas__Empres__4E88ABD4");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Factura> entity);
    }
}
