// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class LogConfiguration : IEntityTypeConfiguration<Log>
    {
        public void Configure(EntityTypeBuilder<Log> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Logs__3214EC074828AD99");

            entity.Property(e => e.Fecha).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IP).HasMaxLength(45);
            entity.Property(e => e.Mensaje)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Nivel)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Empresa).WithMany(p => p.Logs)
                .HasForeignKey(d => d.EmpresaId)
                .HasConstraintName("FK__Logs__EmpresaId__4C6B5938");

            entity.HasOne(d => d.Usuario).WithMany(p => p.Logs)
                .HasForeignKey(d => d.UsuarioId)
                .HasConstraintName("FK__Logs__UsuarioId__4B7734FF");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Log> entity);
    }
}
