// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class LogsSistemaConfiguration : IEntityTypeConfiguration<LogsSistema>
    {
        public void Configure(EntityTypeBuilder<LogsSistema> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__LogsSist__3214EC07051DB951");

            entity.ToTable("LogsSistema");

            entity.Property(e => e.Fecha).HasDefaultValueSql("(sysdatetime())");
            entity.Property(e => e.Mensaje).HasMaxLength(255);
            entity.Property(e => e.Tipo)
                .HasMaxLength(10)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LogsSistema> entity);
    }
}
