// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class SecuenciaNCFConfiguration : IEntityTypeConfiguration<SecuenciaNCF>
    {
        public void Configure(EntityTypeBuilder<SecuenciaNCF> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Secuenci__3214EC074161B57E");

            entity.ToTable("SecuenciaNCF");

            entity.HasIndex(e => new { e.EmpresaId, e.TipoECFId }, "UQ_SecuenciaNCF_Empresa_Tipo").IsUnique();

            entity.Property(e => e.Activo).HasDefaultValue(true);
            entity.Property(e => e.FechaCreacion).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Prefijo).HasMaxLength(10);
            entity.Property(e => e.SecuenciaActual).HasDefaultValue(1);

            entity.HasOne(d => d.Empresa).WithMany(p => p.SecuenciaNCFs)
                .HasForeignKey(d => d.EmpresaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Secuencia__Empre__29221CFB");

            entity.HasOne(d => d.TipoECF).WithMany(p => p.SecuenciaNCFs)
                .HasForeignKey(d => d.TipoECFId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Secuencia__TipoE__2A164134");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SecuenciaNCF> entity);
    }
}
