// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class SecuenciasNCFConfiguration : IEntityTypeConfiguration<SecuenciasNCF>
    {
        public void Configure(EntityTypeBuilder<SecuenciasNCF> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Secuenci__3214EC0731BB99B5");

            entity.ToTable("SecuenciasNCF");

            entity.Property(e => e.TipoECF)
                .HasMaxLength(5)
                .IsUnicode(false);

            entity.HasOne(d => d.Empresa).WithMany(p => p.SecuenciasNCFs)
                .HasForeignKey(d => d.EmpresaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Secuencia__Empre__619B8048");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SecuenciasNCF> entity);
    }
}
