// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SGFE.Domein.Entitys;
using System;
using System.Collections.Generic;

namespace SGFE.Domein.Entitys.Configurations
{
    public partial class TiposECFConfiguration : IEntityTypeConfiguration<TiposECF>
    {
        public void Configure(EntityTypeBuilder<TiposECF> entity)
        {
            entity.HasKey(e => e.Codigo).HasName("PK__TiposECF__06370DAD8BFE4EBF");

            entity.ToTable("TiposECF");

            entity.Property(e => e.Codigo)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Descripcion).HasMaxLength(150);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TiposECF> entity);
    }
}
